title: Lei Huang
position: Ph.D. Student
affiliation: City University of Hong Kong
email: lhuang93-c@my.cityu.edu.hk
keywords: Lei Huang's homepage
google_scholar: https://scholar.google.com/citations?user=xO1oupAAAAAJ&hl=zh-CN
github_link: https://github.com/layne-huang/
linkedin: 
avatar: ./assets/img/photo1.jiff
google_analytics: 
favicon: ./assets/img/logo.png
favicon_dark: ./assets/img/logo.png
description: Lei Huang's homepage.
canonical: https://layne-huang.github.io/
remote_theme: yaoyao-liu/minimal-light
