title: Lei Huang
position: Ph.D. Student
affiliation: City University of Hong Kong
email: lhuang93-c@my.cityu.edu.hk
keywords: Lei Huang's homepage
google_scholar: https://scholar.google.com/citations?user=xO1oupAAAAAJ&hl=zh-CN
github_link: https://github.com/layne-huang/
linkedin: https://www.linkedin.com/in/lei-h-3b7202201/
twitter: https://twitter.com/LHuang_go
avatar: ./assets/img/portrait.jpg
school_bachelor: ./assets/img/whu.png
school_phd: ./assets/img/cityu.png
internship: ./assets/img/tencent.jpg
internship1: ./assets/img/damo.jpeg
visiting: ./assets/img/MIT.jpg
visiting1: ./assets/img/Harvard.jpeg
postdoc: ./assets/img/MGH.jpg
# google_analytics: UA-216510610-1
favicon: ./assets/img/letter-h.png
favicon_dark: ./assets/img/letter-h.png
description: Lei Huang's homepage.
canonical: https://layne-huang.github.io/
remote_theme: yaoyao-liu/minimal-light
